# Generated by Django 3.1.1 on 2020-11-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='uid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
